apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: vote
  labels:
    app: vote-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vote-service
