apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: internal
  labels:
    app: vote-service
spec:
  # temporarily on a load balancer to test
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vote-service
