---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "vote-deployment"
  namespace: internal
  labels:
    app: vote-service
  annotations:
    # Container Image Automated Updates
    fluxcd.io/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-service
  template:
    metadata:
      labels:
        app: vote-service
    spec:
      containers:
        - name: vote-service
          image: 981873564135.dkr.ecr.us-west-2.amazonaws.com/rust-vote-service:4ef2d613
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /vote/health
              port: http
          readinessProbe:
            httpGet:
              path: /vote/~/ready
              port: http
          env:
            - name: RUST_LOG
              value: "info,actix_web=info"
            - name: BASE_PATH
              value: "vote"
            - name: PORT
              value: "8000"
            - name: TABLE_NAME
              value: "WbVotes-stage"
            - name: DYNAMO_REGION
              value: "us-west-2"
            - name: DYNAMO_ENDPOINT
              value: "https://dynamodb.us-west-2.amazonaws.com"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vote-secrets
                  key: database-url
