apiVersion: v1
kind: Service
metadata:
  name: eks-example-service
  namespace: example
  labels:
    app: eks-example
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: eks-example
