apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    minSize: 2
    maxSize: 6
    labels:
      lifetime: OnDemand
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
