apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kong
  namespace: gateway
spec:
  releaseName: kong
  chart:
    repository: https://charts.konghq.com
    name: kong
    version: 1.4.1
  values:
    ingressController:
      installCRDs: false
    admin:
      enabled: true
      http:
        enabled: true
    env:
      - name: KONG_DATABASE
        value: postgres
      - name: KONG_PG_HOST
        value: test.cluster-cui4fpppzxf7.us-west-2.rds.amazonaws.com
      - name: KONG_PG_USER
        value: postgres
      - name: KONG_PG_PORT
        value: 5432
      - NAME: KONG_PG_PASSWORD
        valueFrom:
          secretKeyRef:
            name: gateway-secrets
            key: kong_password
