apiVersion: v1
kind: Service
metadata:
  name: konga-service
  namespace: gateway
  labels:
    app: konga
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: konga
