---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga-deployment
  namespace: gateway
  labels:
    app: konga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
        - name: konga
          image: pantsel/konga
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 1337
              name: http
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: DB_ADAPTER
              value: mysql
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: konga_db_uri
